services:
  neo4j:
    image: neo4j:5.15-community
    environment:
      NEO4J_AUTH: neo4j/password123
      NEO4J_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: true
      NEO4J_apoc_import_file_enabled: true
      NEO4J_dbms_security_procedures_unrestricted: gds.*,apoc.*
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./neo4j:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password123", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - etf-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/11434'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    profiles:
      - gpu
    networks:
      - etf-network

  ollama-cpu:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s bash -c '</dev/tcp/localhost/11434'"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s
    profiles:
      - cpu
    networks:
      - etf-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - OLLAMA_HOST=http://ollama-cpu:11434
      - ALLOWED_TICKERS=["SPY","QQQ","IWM","IJH","IVE","IVW"]
      - LOG_LEVEL=INFO
      - MAX_QUERY_LENGTH=512
      - RESPONSE_CACHE_TTL=3600
    depends_on:
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
        required: false
      ollama-cpu:
        condition: service_healthy
        required: false
    volumes:
      - ./etl:/app/etl
      - api_cache:/app/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - etf-network

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - etf-network

  init:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
      - OLLAMA_HOST=http://ollama-cpu:11434
    depends_on:
      neo4j:
        condition: service_healthy
      api:
        condition: service_healthy
      ollama:
        condition: service_healthy
        required: false
      ollama-cpu:
        condition: service_healthy
        required: false
    volumes:
      - ./neo4j:/app/neo4j
      - ./etl:/app/etl
    profiles:
      - init
    networks:
      - etf-network

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  ollama_data:
    driver: local
  api_cache:
    driver: local

networks:
  etf-network:
    driver: bridge
    name: etf-graphrag-network